# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f09f90d3622dd11d9cd04cdfa5b16a285cb00577c4a29c27b4e898e72adde9296954fb4035db27fe0fb4a7bfa89054d990f8d326b12a0fa03367869373f2cdb

test:
  secret_key_base: bd1e854bd0ca0f4f51a1f86f5a0e2c14dad59e87ddb90f68e333b3f75e1bf0ff11e0874af4263754dfc624c558f0f8f2f1de7c6787f743d6aec89dd3cf725b67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
