namespace :morning do
  desc "Turn off the alarm"
  task :turn_off_alarm do
    puts "Turned off the goddamn alarm"
  end

  desc "Make myself a fancy man"
  task :groom_self do
    puts "Brush teeth"
    puts "Butter armpits"
    puts "Wax beard"
  end

  desc "Make some coffee (set an environment variable COFFEE_CUPS to customise)"
  task :make_coffee do
    cups = ENV['COFFEE_CUPS'] || 2
    puts "Make #{ cups } cups of coffee"
  end

  desc "That horrible little dog"
  task :walk_dog do
    puts "Walk the horrible little dog"
  end

  desc "Get ready for another exciting day"
  task :get_ready => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
    puts "Ready to leave the house"
  end
end

task :default => 'morning:get_ready'

namespace :morning do
  task :groom_self do
    puts "Shave eyebrows"
  end
end

namespace :afternoon do
  desc "Make special afternoon coffee"
  task :make_coffee do
    Rake::Task['morning:make_coffee'].invoke
    puts "Add bourbon"
  end
end
