# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3d2cbc3561df8ca06ab27d9f71d7e5b662db4f71799a253a90f5d4fb154e4738d32f00deb668d8a806a0145d35a379d9d178b17dec2c463db090fbeb4f0ad7

test:
  secret_key_base: 2c999dc317d24394b0c2b03be5a9c94f143e6e2bd96f658715353af37d0d4e6ff82f0ef28b85ddda1698316fabc3adac05b08c0444a0d8ecfabdd855d4bf616e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
