# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33d7ca8f4b0720782a5df5e84631cc9961da7f068595700690224c6f121fb9a6f9a3acd91bf7dfdddeea33e9fedb6cd2a454a5428940c343090730fd82f12231
  sendgrid_apikey: <%= ENV['SENDGRID_APIKEY'] %>

test:
  secret_key_base: a199e7abd0cbdf2e10051d60ffa330a9ca549f5a7fd1a18386a06aab7cb4284959f3beeda2901b52ed28cd3eafc363877606645a2e0af267b512cac06212d24d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_apikey: <%= ENV['SENDGRID_APIKEY'] %>
